name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: name/app
          
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to aliyun
      uses: docker/login-action@v3
      with:
        registry: registry.cn-shenzhen.aliyuncs.com
        username: ${{ secrets.ALIYUNACR_USERNAME }}
        password: ${{ secrets.ALIYUNACR_PASSWORD }}
          
    - name: Get Git short ref
      id: short_ref
      run: echo "SHORT_REF=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aiclient2api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/aiclient2api:${{ env.SHORT_REF }}
          registry.cn-shenzhen.aliyuncs.com/janeyre/aiclient2api:latest
          registry.cn-shenzhen.aliyuncs.com/janeyre/aiclient2api:${{ env.SHORT_REF }}
        labels: ${{ steps.meta.outputs.labels }}
          
